main:htonl inet_aton  inet_netof inet_ntoa inet_addr inet_lnaof inet_network inet_makeaddr

htonl:htonl.c
	gcc htonl.c -o htonl

inet_aton:inet_aton.c
	gcc inet_aton.c -o inet_aton

inet_netof:inet_netof.c
	gcc inet_netof.c -o inet_netof

inet_ntoa:inet_ntoa.c
	gcc inet_ntoa.c -o inet_ntoa

inet_addr:inet_addr.c
	gcc inet_addr.c -o inet_addr

inet_lnaof:inet_lnaof.c
	gcc inet_lnaof.c -o inet_lnaof

inet_network:inet_network.c
	gcc inet_network.c -o inet_network

inet_makeaddr:inet_makeaddr.c
	gcc inet_makeaddr.c -o inet_makeaddr


clean:
	rm htonl inet_aton  inet_netof inet_ntoa inet_addr inet_lnaof inet_network inet_makeaddr

